// ─── DeutschForge Vocabulary Book ─────────────────────────────────────────────
// 28 sections of A1/A2 German vocabulary with English translations

export interface BookWord {
  german: string;
  english: string;
}

export interface BookSection {
  id: string;
  number: number;
  name: string;
  words: BookWord[];
}

export const BOOK_SECTIONS: BookSection[] = [
  {
    id: "section-1",
    number: 1,
    name: "Mein Körper",
    words: [
      { german: "die Haare", english: "hair" },
      { german: "die Stirn", english: "forehead" },
      { german: "das Auge", english: "eye" },
      { german: "das Ohr", english: "ear" },
      { german: "die Backe", english: "cheek" },
      { german: "der Mund", english: "mouth" },
      { german: "die Zunge", english: "tongue" },
      { german: "das Kinn", english: "chin" },
      { german: "die Augenbraue", english: "eyebrow" },
      { german: "das Lid", english: "eyelid" },
      { german: "die Wimpern", english: "eyelashes" },
      { german: "die Nase", english: "nose" },
      { german: "das Nasenloch", english: "nostril" },
      { german: "die Lippe", english: "lip" },
      { german: "der Zahn", english: "tooth" },
      { german: "der Kopf", english: "head" },
      { german: "der Hals", english: "neck" },
      { german: "die Schulter", english: "shoulder" },
      { german: "die Brust", english: "chest" },
      { german: "die Brustwarze", english: "nipple" },
      { german: "der Bauchnabel", english: "belly button" },
      { german: "der Bauch", english: "belly" },
      { german: "die Hand", english: "hand" },
      { german: "der Finger", english: "finger" },
      { german: "die Scheide", english: "vagina" },
      { german: "der Fuß", english: "foot" },
      { german: "der Zeh", english: "toe" },
      { german: "der Nacken", english: "nape" },
      { german: "der Rücken", english: "back" },
      { german: "der Arm", english: "arm" },
      { german: "der Ellenbogen", english: "elbow" },
      { german: "der Po", english: "bottom" },
      { german: "das Glied", english: "penis" },
      { german: "das Bein", english: "leg" },
      { german: "das Knie", english: "knee" },
      { german: "der Knöchel", english: "ankle" },
      { german: "die Ferse", english: "heel" },
    ],
  },
  {
    id: "section-2",
    number: 2,
    name: "Die Kleidung",
    words: [
      { german: "das Unterhemd", english: "undershirt" },
      { german: "die Unterhose", english: "underpants" },
      { german: "die Socken", english: "socks" },
      { german: "die Strümpfe", english: "stockings" },
      { german: "die Strumpfhose", english: "tights" },
      { german: "die Bluse", english: "blouse" },
      { german: "das Hemd", english: "shirt" },
      { german: "der Knopf", english: "button" },
      { german: "der Rock", english: "skirt" },
      { german: "das T-Shirt", english: "t-shirt" },
      { german: "die Hose", english: "trousers" },
      { german: "die Latzhose", english: "dungarees" },
      { german: "das Nachthemd", english: "nightgown" },
      { german: "der Schlafanzug", english: "pyjamas" },
      { german: "die Strickjacke", english: "cardigan" },
      { german: "der Pullover", english: "sweater" },
      { german: "der Gürtel", english: "belt" },
      { german: "die Jeans", english: "jeans" },
      { german: "der Trainingsanzug", english: "tracksuit" },
      { german: "der Reißverschluss", english: "zipper" },
      { german: "das Sweatshirt", english: "sweatshirt" },
      { german: "die kurze Hose", english: "shorts" },
      { german: "die Jacke", english: "jacket" },
      { german: "die Schuhe", english: "shoes" },
      { german: "die Sandalen", english: "sandals" },
      { german: "die Turnschuhe", english: "trainers" },
      { german: "die Hausschuhe", english: "slippers" },
      { german: "die Gummistiefel", english: "rubber boots" },
      { german: "die Mütze", english: "beanie" },
      { german: "der Mantel", english: "coat" },
      { german: "der Anorak", english: "anorak" },
      { german: "der Schal", english: "scarf" },
      { german: "die Handschuhe", english: "gloves" },
      { german: "der Kleiderbügel", english: "clothes hanger" },
      { german: "das Kleid", english: "dress" },
      { german: "der Regenschirm", english: "umbrella" },
      { german: "der Kleiderschrank", english: "wardrobe" },
      { german: "die Regenjacke", english: "rain jacket" },
      { german: "der Bikini", english: "bikini" },
      { german: "der Badeanzug", english: "swimsuit" },
      { german: "die Armbanduhr", english: "wristwatch" },
      { german: "die Halskette", english: "necklace" },
      { german: "der Ring", english: "ring" },
      { german: "der Ohrring", english: "earring" },
      { german: "die Brille", english: "glasses" },
      { german: "das Armband", english: "bracelet" },
      { german: "der Schmuck", english: "jewellery" },
      { german: "die Badehose", english: "swimming trunks" },
    ],
  },
  {
    id: "section-3",
    number: 3,
    name: "Die Familie",
    words: [
      { german: "die Frau", english: "woman/wife" },
      { german: "der Mann", english: "man/husband" },
      { german: "die Erwachsenen", english: "adults" },
      { german: "das Mädchen", english: "girl" },
      { german: "der Junge", english: "boy" },
      { german: "das Baby", english: "baby" },
      { german: "die Kinder", english: "children" },
      { german: "die Haustiere", english: "pets" },
      { german: "die Eltern", english: "parents" },
      { german: "die Mutter", english: "mother" },
      { german: "der Vater", english: "father" },
      { german: "der Sohn", english: "son" },
      { german: "die Tochter", english: "daughter" },
      { german: "der Ehemann", english: "husband" },
      { german: "die Ehefrau", english: "wife" },
      { german: "das Ehepaar", english: "married couple" },
      { german: "der Bruder", english: "brother" },
      { german: "die Schwester", english: "sister" },
      { german: "die Geschwister", english: "siblings" },
      { german: "die Großeltern", english: "grandparents" },
      { german: "der Großvater", english: "grandfather" },
      { german: "die Großmutter", english: "grandmother" },
      { german: "der Enkel", english: "grandson" },
      { german: "die Enkelin", english: "granddaughter" },
      { german: "die Enkelkinder", english: "grandchildren" },
      { german: "der Onkel", english: "uncle" },
      { german: "die Tante", english: "aunt" },
      { german: "der Neffe", english: "nephew" },
      { german: "die Nichte", english: "niece" },
      { german: "der Cousin", english: "cousin (m)" },
      { german: "die Cousine", english: "cousin (f)" },
    ],
  },
  {
    id: "section-4",
    number: 4,
    name: "Das Haus",
    words: [
      { german: "die Hausnummer", english: "house number" },
      { german: "die Klingel", english: "doorbell" },
      { german: "das Namensschild", english: "name plate" },
      { german: "der Briefkasten", english: "letterbox" },
      { german: "das Türschloss", english: "door lock" },
      { german: "der Schlüssel", english: "key" },
      { german: "der Dachziegel", english: "roof tile" },
      { german: "der Schornstein", english: "chimney" },
      { german: "das Dachfenster", english: "skylight" },
      { german: "das Dach", english: "roof" },
      { german: "die Regenrinne", english: "gutter" },
      { german: "das Badezimmer", english: "bathroom" },
      { german: "das Kinderzimmer", english: "children's room" },
      { german: "das Wohnzimmer", english: "living room" },
      { german: "das Kellerfenster", english: "basement window" },
      { german: "die Mülltonnen", english: "bins" },
      { german: "die Treppe", english: "stairs" },
      { german: "die Haustür", english: "front door" },
      { german: "der Blumenkasten", english: "window box" },
      { german: "der Fensterladen", english: "shutter" },
      { german: "das Fensterbrett", english: "windowsill" },
      { german: "das Rollo", english: "blind" },
      { german: "das Fenster", english: "window" },
      { german: "die Wand", english: "wall" },
      { german: "die Hecke", english: "hedge" },
      { german: "der Dachboden", english: "attic" },
      { german: "die Wäscheleine", english: "clothesline" },
      { german: "der Wäschekorb", english: "laundry basket" },
      { german: "die Antenne", english: "antenna" },
      { german: "die Wäscheklammer", english: "clothes peg" },
      { german: "der Eimer", english: "bucket" },
      { german: "der Putzlappen", english: "cleaning cloth" },
      { german: "der Schrubber", english: "scrubber" },
      { german: "der Besen", english: "broom" },
      { german: "die Kehrschaufel", english: "dustpan" },
      { german: "der Handfeger", english: "hand brush" },
      { german: "der Staubsauger", english: "vacuum cleaner" },
      { german: "der Flur", english: "hallway" },
      { german: "das Esszimmer", english: "dining room" },
      { german: "die Abstellkammer", english: "storage room" },
      { german: "das Bügeleisen", english: "iron" },
      { german: "das Bügelbrett", english: "ironing board" },
      { german: "der Keller", english: "cellar" },
      { german: "das Schlafzimmer", english: "bedroom" },
      { german: "der Balkon", english: "balcony" },
      { german: "die Garage", english: "garage" },
      { german: "das Garagentor", english: "garage door" },
      { german: "die Küche", english: "kitchen" },
      { german: "die Einfahrt", english: "driveway" },
    ],
  },
  {
    id: "section-5",
    number: 5,
    name: "In der Küche",
    words: [
      { german: "die Auflaufform", english: "baking dish" },
      { german: "der Deckel", english: "lid" },
      { german: "der Topf", english: "pot" },
      { german: "die Pfanne", english: "frying pan" },
      { german: "der Topflappen", english: "oven glove" },
      { german: "der Schwamm", english: "sponge" },
      { german: "die Küchenrolle", english: "kitchen roll" },
      { german: "der Schrank", english: "cupboard" },
      { german: "die Dunstabzugshaube", english: "extractor hood" },
      { german: "die Bürste", english: "brush" },
      { german: "die Spüle", english: "sink" },
      { german: "das Geschirrtuch", english: "dish towel" },
      { german: "der Herd", english: "stove" },
      { german: "der Backofen", english: "oven" },
      { german: "das Spülmittel", english: "washing-up liquid" },
      { german: "die Zitronenpresse", english: "lemon squeezer" },
      { german: "die Kuchenform", english: "cake tin" },
      { german: "das Nudelholz", english: "rolling pin" },
      { german: "der Mülleimer", english: "bin" },
      { german: "das Rührgerät", english: "mixer" },
      { german: "die Schüssel", english: "bowl" },
      { german: "die Waage", english: "scales" },
      { german: "die Geschirrspülmaschine", english: "dishwasher" },
      { german: "das Sieb", english: "sieve" },
      { german: "die Reibe", english: "grater" },
      { german: "der Teller", english: "plate" },
      { german: "der Suppenteller", english: "soup plate" },
      { german: "die Tasse", english: "cup" },
      { german: "die Untertasse", english: "saucer" },
      { german: "der Becher", english: "mug" },
      { german: "das Geschirr", english: "crockery" },
      { german: "der Eierbecher", english: "egg cup" },
      { german: "das Glas", english: "glass" },
      { german: "die Mikrowelle", english: "microwave" },
      { german: "die Gewürze", english: "spices" },
      { german: "die Kaffeemaschine", english: "coffee machine" },
      { german: "der Toaster", english: "toaster" },
      { german: "der Kühlschrank", english: "fridge" },
      { german: "das Messer", english: "knife" },
      { german: "die Gabel", english: "fork" },
      { german: "der Esslöffel", english: "tablespoon" },
      { german: "der Teelöffel", english: "teaspoon" },
      { german: "der Schneebesen", english: "whisk" },
      { german: "das Besteck", english: "cutlery" },
      { german: "die Schublade", english: "drawer" },
      { german: "das Küchenmesser", english: "kitchen knife" },
      { german: "das Brett", english: "board" },
      { german: "das Backblech", english: "baking tray" },
      { german: "die Dose", english: "tin/can" },
      { german: "der Dosenöffner", english: "tin opener" },
      { german: "der Korkenzieher", english: "corkscrew" },
      { german: "die Schürze", english: "apron" },
      { german: "der Gefrierschrank", english: "freezer" },
      { german: "die Suppenkelle", english: "ladle" },
      { german: "der Kochlöffel", english: "wooden spoon" },
      { german: "der Pfannenwender", english: "spatula" },
    ],
  },

  {
    id: "section-6",
    number: 6,
    name: "Beim Essen",
    words: [
      { german: "die Suppe", english: "soup" },
      { german: "die Pizza", english: "pizza" },
      { german: "das Spiegelei", english: "fried egg" },
      { german: "die Spaghetti", english: "spaghetti" },
      { german: "die Soße", english: "sauce/gravy" },
      { german: "der Toast", english: "toast" },
      { german: "das Brot", english: "bread" },
      { german: "der Tee", english: "tea" },
      { german: "das Tablett", english: "tray" },
      { german: "der Fisch", english: "fish" },
      { german: "der Brotkorb", english: "bread basket" },
      { german: "das Brötchen", english: "bread roll" },
      { german: "die Zuckerdose", english: "sugar bowl" },
      { german: "die Fischstäbchen", english: "fish fingers" },
      { german: "der Käse", english: "cheese" },
      { german: "die Wurst", english: "sausage/cold cuts" },
      { german: "der Braten", english: "roast" },
      { german: "die Milch", english: "milk" },
      { german: "das Müsli", english: "muesli/cereal" },
      { german: "der Honig", english: "honey" },
      { german: "das Hähnchen", english: "chicken" },
      { german: "der Kakao", english: "cocoa/hot chocolate" },
      { german: "das Schnitzel", english: "schnitzel" },
      { german: "die Bratwurst", english: "grilled sausage" },
      { german: "der Hamburger", english: "hamburger" },
      { german: "die Pommes frites", english: "french fries" },
      { german: "der Reis", english: "rice" },
      { german: "die Bratkartoffeln", english: "fried potatoes" },
      { german: "das Gemüse", english: "vegetables" },
      { german: "die Brezel", english: "pretzel" },
      { german: "das Ei", english: "egg" },
      { german: "der Salat", english: "salad/lettuce" },
      { german: "die Schokocreme", english: "chocolate spread" },
      { german: "die Kanne", english: "pot/jug" },
      { german: "der Pudding", english: "pudding" },
      { german: "der Kaffee", english: "coffee" },
      { german: "der Kuchen", english: "cake" },
      { german: "die Butter", english: "butter" },
      { german: "die Marmelade", english: "jam/marmalade" },
      { german: "das Eis", english: "ice cream" },
      { german: "das Milchkännchen", english: "milk jug" },
      { german: "der Quark", english: "quark/curd cheese" },
      { german: "der Saft", english: "juice" },
      { german: "die Tischdecke", english: "tablecloth" },
      { german: "der Ketchup", english: "ketchup" },
      { german: "der Senf", english: "mustard" },
      { german: "der Salzstreuer", english: "salt shaker" },
      { german: "die Pfeffermühle", english: "pepper mill" },
      { german: "die Serviette", english: "napkin" },
    ],
  },
  {
    id: "section-7",
    number: 7,
    name: "Im Badezimmer",
    words: [
      { german: "der Abfluss", english: "drain" },
      { german: "der Stöpsel", english: "plug/stopper" },
      { german: "der Waschbeutel", english: "wash bag/toiletry bag" },
      { german: "das Nagelsetui", english: "nail kit" },
      { german: "die Wärmflasche", english: "hot water bottle" },
      { german: "das Schminkzeug", english: "make-up/cosmetics" },
      { german: "der Lippenstift", english: "lipstick" },
      { german: "der Wasserhahn", english: "tap/faucet" },
      { german: "der Wäschetrockner", english: "tumble dryer" },
      { german: "die Waschmaschine", english: "washing machine" },
      { german: "der Schaum", english: "foam/lather" },
      { german: "das Parfüm", english: "perfume" },
      { german: "das Deodorant", english: "deodorant" },
      { german: "die Brause", english: "shower head/spray" },
      { german: "die Dusche", english: "shower" },
      { german: "die Badematte", english: "bath mat" },
      { german: "der Waschlappen", english: "washcloth/flannel" },
      { german: "die Badewanne", english: "bathtub" },
      { german: "die Toilettenbürste", english: "toilet brush" },
      { german: "der Duschvorhang", english: "shower curtain" },
      { german: "der Handtuchhalter", english: "towel rail" },
      { german: "der Heizkörper", english: "radiator" },
      { german: "das Rasierwasser", english: "aftershave" },
      { german: "die Haarspange", english: "hair clip" },
      { german: "das Haargummi", english: "hair tie/elastic" },
      { german: "der Kamm", english: "comb" },
      { german: "die Bürste", english: "brush" },
      { german: "die Fliesen", english: "tiles" },
      { german: "das Toilettenpapier", english: "toilet paper" },
      { german: "der Fön", english: "hair dryer" },
      { german: "das Handtuch", english: "towel" },
      { german: "die Personenwaage", english: "bathroom scales" },
      { german: "der Bademantel", english: "bathrobe" },
      { german: "die Wäsche", english: "laundry/underwear" },
      { german: "der Spiegel", english: "mirror" },
      { german: "die Ablage", english: "shelf/ledge" },
      { german: "das Waschbecken", english: "washbasin/sink" },
      { german: "der Zahnputzbecher", english: "toothbrush cup" },
      { german: "die Zahnbürste", english: "toothbrush" },
      { german: "die Zahnpasta", english: "toothpaste" },
      { german: "die Watte", english: "cotton wool" },
      { german: "die Creme", english: "cream/lotion" },
      { german: "die Seife", english: "soap" },
      { german: "das Duschgel", english: "shower gel" },
      { german: "der Rasierapparat", english: "electric razor/shaver" },
      { german: "das Haarspray", english: "hair spray" },
      { german: "das Shampoo", english: "shampoo" },
      { german: "das Schaumbad", english: "bubble bath" },
      { german: "die Toilette", english: "toilet" },
    ],
  },
  {
    id: "section-8",
    number: 8,
    name: "Im Wohnzimmer",
    words: [
      { german: "der Videorecorder", english: "video recorder" },
      { german: "die Videokassette", english: "video cassette" },
      { german: "der Schallplattenspieler", english: "record player" },
      { german: "die Schallplatte", english: "vinyl record" },
      { german: "der CD-Spieler", english: "CD player" },
      { german: "das Radio", english: "radio" },
      { german: "der Kassettenrecorder", english: "cassette recorder" },
      { german: "die Kassette", english: "cassette" },
      { german: "der Fernseher", english: "television" },
      { german: "die Schrankwand", english: "wall unit/cabinet" },
      { german: "der Vogelkäfig", english: "birdcage" },
      { german: "das Brennholz", english: "firewood" },
      { german: "die Box", english: "speaker box" },
      { german: "die Kopfhörer", english: "headphones" },
      { german: "die Stereoanlage", english: "stereo system" },
      { german: "die CD", english: "CD" },
      { german: "der Teppich", english: "carpet/rug" },
      { german: "der Stuhl", english: "chair" },
      { german: "die Kerze", english: "candle" },
      { german: "der Kerzenständer", english: "candle holder" },
      { german: "die Obstschale", english: "fruit bowl" },
      { german: "der Tisch", english: "table" },
      { german: "das Bild", english: "picture/painting" },
      { german: "das Foto", english: "photo" },
      { german: "der Kamin", english: "fireplace" },
      { german: "das Feuer", english: "fire" },
      { german: "die Vase", english: "vase" },
      { german: "die Topfpflanze", english: "potted plant" },
      { german: "das Telefon", english: "telephone" },
      { german: "die Gardine", english: "net curtain" },
      { german: "die Lampe", english: "lamp" },
      { german: "der Kaktus", english: "cactus" },
      { german: "die Fernbedienung", english: "remote control" },
      { german: "die Glühbirne", english: "light bulb" },
      { german: "die Steckdose", english: "plug socket/outlet" },
      { german: "die Zeitung", english: "newspaper" },
      { german: "das Buch", english: "book" },
      { german: "das Kissen", english: "cushion/pillow" },
      { german: "die Streichhölzer", english: "matches" },
      { german: "der Sessel", english: "armchair" },
      { german: "das Sofa", english: "sofa/couch" },
      { german: "die Illustrierte", english: "magazine" },
    ],
  },
  {
    id: "section-9",
    number: 9,
    name: "Im Kinderzimmer",
    words: [
      { german: "die Puppe", english: "doll" },
      { german: "der Puppenwagen", english: "doll's pram" },
      { german: "die Handpuppe", english: "hand puppet" },
      { german: "die Marionette", english: "marionette/puppet" },
      { german: "das Kuscheltier", english: "soft toy/stuffed animal" },
      { german: "das Spielzeugauto", english: "toy car" },
      { german: "das Poster", english: "poster" },
      { german: "der Teddy", english: "teddy bear" },
      { german: "die Leiter", english: "ladder" },
      { german: "das Etagenbett", english: "bunk bed" },
      { german: "der Kaufmannsladen", english: "toy shop/play store" },
      { german: "der Ball", english: "ball" },
      { german: "der Luftballon", english: "balloon" },
      { german: "der Vorhang", english: "curtain" },
      { german: "der Wecker", english: "alarm clock" },
      { german: "das Puppenhaus", english: "dolls' house" },
      { german: "das Kartenspiel", english: "card game" },
      { german: "das Puzzle", english: "puzzle/jigsaw" },
      { german: "der Gameboy", english: "Game Boy" },
      { german: "der Computer", english: "computer" },
      { german: "der Schreibtisch", english: "desk" },
      { german: "der Schreibtischstuhl", english: "desk chair" },
      { german: "die Eisenbahn", english: "toy train/railway" },
      { german: "die Bauklötze", english: "building blocks" },
      { german: "die Rechenmaschine", english: "calculator" },
      { german: "das Regal", english: "shelf" },
      { german: "die Trommel", english: "drum" },
      { german: "die Spielfiguren", english: "playing pieces/figures" },
      { german: "die Spielkiste", english: "toy box" },
      { german: "die Murmeln", english: "marbles" },
      { german: "der Comic", english: "comic book" },
      { german: "die Legosteine", english: "Lego bricks" },
      { german: "das Spielbrett", english: "game board" },
      { german: "das Steckenpferd", english: "hobby horse" },
      { german: "das Xylophon", english: "xylophone" },
      { german: "die Blockflöte", english: "recorder (instrument)" },
      { german: "die Gitarre", english: "guitar" },
      { german: "der Würfel", english: "dice" },
      { german: "die Spielsteine", english: "game pieces/counters" },
    ],
  },
  {
    id: "section-10",
    number: 10,
    name: "Im Garten",
    words: [
      { german: "der Krokus", english: "crocus" },
      { german: "die Mohnblume", english: "poppy" },
      { german: "die Narzissen", english: "daffodils" },
      { german: "die Tulpe", english: "tulip" },
      { german: "die Blüte", english: "blossom/bloom" },
      { german: "der Stängel", english: "stem/stalk" },
      { german: "das Blatt", english: "leaf" },
      { german: "der Löwenzahn", english: "dandelion" },
      { german: "das Vergissmeinnicht", english: "forget-me-not" },
      { german: "die Sonnenblume", english: "sunflower" },
      { german: "der Zaun", english: "fence" },
      { german: "das Blumenbeet", english: "flower bed" },
      { german: "der Busch", english: "bush/shrub" },
      { german: "die Kräuter", english: "herbs" },
      { german: "der Rasen", english: "lawn/grass" },
      { german: "das Planschbecken", english: "paddling pool" },
      { german: "der Rechen", english: "rake" },
      { german: "der Schmetterling", english: "butterfly" },
      { german: "die Rosen", english: "roses" },
      { german: "die Margeriten", english: "daisies/marguerites" },
      { german: "das Maiglöckchen", english: "lily of the valley" },
      { german: "die Gänseblümchen", english: "daisies" },
      { german: "der Flieder", english: "lilac" },
      { german: "die Kletterpflanze", english: "climbing plant" },
      { german: "das Gemüsebeet", english: "vegetable patch" },
      { german: "der Gartenschlauch", english: "garden hose" },
      { german: "der Komposthaufen", english: "compost heap" },
      { german: "der Rasenmäher", english: "lawn mower" },
      { german: "der Grill", english: "barbecue/grill" },
      { german: "die Libelle", english: "dragonfly" },
      { german: "die Seerose", english: "water lily" },
      { german: "der Teich", english: "pond" },
      { german: "die Raupe", english: "caterpillar" },
      { german: "der Marienkäfer", english: "ladybird/ladybug" },
      { german: "die Schnecke", english: "snail/slug" },
      { german: "die Fliege", english: "fly" },
      { german: "die Biene", english: "bee" },
      { german: "die Hacke", english: "hoe" },
      { german: "der Spaten", english: "spade" },
      { german: "die Gießkanne", english: "watering can" },
      { german: "die Gartenschere", english: "garden shears/secateurs" },
      { german: "die Pflanzkelle", english: "trowel" },
      { german: "die Samen", english: "seeds" },
      { german: "die Blumenzwiebel", english: "flower bulb" },
      { german: "der Regenwurm", english: "earthworm" },
      { german: "das Gewächshaus", english: "greenhouse" },
      { german: "der Geräteschuppen", english: "tool shed" },
      { german: "die Erde", english: "soil/earth" },
      { german: "die Terrasse", english: "terrace/patio" },
      { german: "die Holzkohle", english: "charcoal" },
      { german: "der Oleander", english: "oleander" },
      { german: "der Blumentopf", english: "flower pot" },
    ],
  },
  {
    id: "section-11",
    number: 11,
    name: "Auf dem Spielplatz",
    words: [
      { german: "das Fahrrad", english: "bicycle" },
      { german: "der Roller", english: "scooter" },
      { german: "das Dreirad", english: "tricycle" },
      { german: "der Sturzhelm", english: "crash helmet" },
      { german: "das Skateboard", english: "skateboard" },
      { german: "die Rollschuhe", english: "roller skates" },
      { german: "der Kletterturm", english: "climbing tower" },
      { german: "das Karussell", english: "merry-go-round" },
      { german: "die Jogger", english: "jogger" },
      { german: "das Kletternetz", english: "climbing net" },
      { german: "die Tischtennisplatte", english: "table tennis table" },
      { german: "der Park", english: "park" },
      { german: "die Seilbahn", english: "zip line/cable car" },
      { german: "der Kinderwagen", english: "pushchair/pram" },
      { german: "das Baumhaus", english: "treehouse" },
      { german: "das Holzhaus", english: "wooden house/play house" },
      { german: "die Hängebrücke", english: "suspension bridge" },
      { german: "die Rutsche", english: "slide" },
      { german: "die Wippe", english: "seesaw" },
      { german: "die Parkbank", english: "park bench" },
      { german: "der Sand", english: "sand" },
      { german: "der Sandkasten", english: "sandpit" },
      { german: "der Fußball", english: "football/soccer ball" },
      { german: "das Springseil", english: "skipping rope" },
      { german: "das Frisbee", english: "frisbee" },
      { german: "der Federballschläger", english: "badminton racket" },
      { german: "der Federball", english: "shuttlecock" },
      { german: "der Tischtennisschläger", english: "table tennis bat" },
      { german: "der Drachen", english: "kite" },
      { german: "der Walkman", english: "Walkman" },
      { german: "die Schaukel", english: "swing" },
    ],
  },
  {
    id: "section-12",
    number: 12,
    name: "In der Schule",
    words: [
      { german: "das Pausenbrot", english: "packed lunch/snack" },
      { german: "die Garderobe", english: "cloakroom/coat rack" },
      { german: "das Zeugnis", english: "school report/certificate" },
      { german: "der Schulranzen", english: "school bag/satchel" },
      { german: "das Schulbuch", english: "textbook" },
      { german: "der Ordner", english: "folder/binder" },
      { german: "der Farbkasten", english: "paint box" },
      { german: "der Schulhof", english: "school yard/playground" },
      { german: "die Bücher", english: "books" },
      { german: "die Leseecke", english: "reading corner" },
      { german: "der Buchstabe", english: "letter (of alphabet)" },
      { german: "das Blatt", english: "sheet of paper/leaf" },
      { german: "der Pinsel", english: "paintbrush" },
      { german: "das Lineal", english: "ruler" },
      { german: "das Klassenzimmer", english: "classroom" },
      { german: "die Tafel", english: "blackboard/whiteboard" },
      { german: "die Zahl", english: "number" },
      { german: "die Kreide", english: "chalk" },
      { german: "das Klassenbuch", english: "class register" },
      { german: "das Pult", english: "teacher's desk/lectern" },
      { german: "der Papierkorb", english: "wastepaper basket" },
      { german: "der Setzkasten", english: "type case/sorting box" },
      { german: "die Rechenaufgabe", english: "arithmetic problem" },
      { german: "der Schwamm", english: "sponge/board eraser" },
      { german: "die Lehrerin", english: "teacher (f)" },
      { german: "die Schülerin", english: "pupil (f)" },
      { german: "die Zeichnung", english: "drawing" },
      { german: "der Kartenständer", english: "map stand" },
      { german: "die Landkarte", english: "map" },
      { german: "das Wort", english: "word" },
      { german: "das Alphabet", english: "alphabet" },
      { german: "der Schüler", english: "pupil (m)" },
      { german: "das Heft", english: "exercise book" },
      { german: "der Zeichenblock", english: "drawing pad/sketchbook" },
      { german: "der Tesafilm", english: "sticky tape/Sellotape" },
      { german: "der Klebstoff", english: "glue/adhesive" },
      { german: "das Federmäppchen", english: "pencil case" },
      { german: "der Bleistift", english: "pencil" },
      { german: "der Buntstift", english: "coloured pencil/crayon" },
      { german: "der Wachsmalstift", english: "wax crayon" },
      { german: "der Filzstift", english: "felt-tip pen" },
      { german: "der Kugelschreiber", english: "ballpoint pen/biro" },
      { german: "der Füller", english: "fountain pen" },
      { german: "die Patrone", english: "ink cartridge" },
      { german: "der Spitzer", english: "pencil sharpener" },
      { german: "der Zirkel", english: "compass (drawing)" },
      { german: "die Schere", english: "scissors" },
      { german: "der Radiergummi", english: "eraser/rubber" },
    ],
  },
  {
    id: "section-13",
    number: 13,
    name: "In der Stadt",
    words: [
      { german: "die Reklame", english: "advertisement/billboard" },
      { german: "die Litfaßsäule", english: "advertising column" },
      { german: "der Briefkasten", english: "postbox/mailbox" },
      { german: "die Telefonzelle", english: "phone box/booth" },
      { german: "der Straßenmaler", english: "street artist/pavement artist" },
      { german: "der Straßenmusikant", english: "street musician/busker" },
      { german: "die Müllcontainer", english: "rubbish bins/dumpsters" },
      { german: "das Restaurant", english: "restaurant" },
      { german: "das Hotel", english: "hotel" },
      { german: "der Kirchturm", english: "church tower/steeple" },
      { german: "die Kirche", english: "church" },
      { german: "die Straße", english: "street/road" },
      { german: "das Taxi", english: "taxi" },
      { german: "das Rathaus", english: "town hall" },
      { german: "der Gehweg", english: "pavement/sidewalk" },
      { german: "das Kino", english: "cinema" },
      { german: "der Imbiss", english: "snack bar/fast food stall" },
      { german: "die Apotheke", english: "pharmacy" },
      { german: "das Café", english: "café" },
      { german: "das Museum", english: "museum" },
      { german: "der Blumenladen", english: "flower shop" },
      { german: "der Brunnen", english: "fountain/well" },
      { german: "die Fußgängerzone", english: "pedestrian zone" },
      { german: "das Kaufhaus", english: "department store" },
      { german: "das Schaufenster", english: "shop window" },
      { german: "die Kreuzung", english: "crossroads/intersection" },
      { german: "der Polizist", english: "police officer" },
      { german: "der Zebrastreifen", english: "pedestrian crossing/zebra crossing" },
      { german: "die U-Bahn", english: "subway/metro" },
      { german: "das Büro", english: "office" },
      { german: "die Bank", english: "bank" },
      { german: "die Haltestelle", english: "bus/tram stop" },
      { german: "die Parkuhr", english: "parking meter" },
      { german: "die Straßenlaterne", english: "street lamp" },
      { german: "die Ampel", english: "traffic light" },
      { german: "das Straßenschild", english: "street sign" },
      { german: "das Ortsschild", english: "place name sign" },
      { german: "der Unfall", english: "accident" },
      { german: "die Fußgänger", english: "pedestrians" },
    ],
  },
  {
    id: "section-14",
    number: 14,
    name: "Der Verkehr",
    words: [
      { german: "das Segelflugzeug", english: "glider" },
      { german: "der Flughafen", english: "airport" },
      { german: "das Flugzeug", english: "airplane" },
      { german: "der Hubschrauber", english: "helicopter" },
      { german: "der Tower", english: "control tower" },
      { german: "die Gangway", english: "gangway/boarding bridge" },
      { german: "das Cockpit", english: "cockpit" },
      { german: "der Pilot", english: "pilot" },
      { german: "die Stewardess", english: "flight attendant" },
      { german: "der Hafen", english: "harbour/port" },
      { german: "die Fähre", english: "ferry" },
      { german: "das Motorboot", english: "motorboat" },
      { german: "das Schiff", english: "ship" },
      { german: "der Kapitän", english: "captain" },
      { german: "der Matrose", english: "sailor/seaman" },
      { german: "der Anker", english: "anchor" },
      { german: "das Luftkissenboot", english: "hovercraft" },
      { german: "der Bahnhof", english: "train station" },
      { german: "die Lokomotive", english: "locomotive/engine" },
      { german: "der Waggon", english: "railway carriage/wagon" },
      { german: "der Zug", english: "train" },
      { german: "das Signal", english: "signal" },
      { german: "der Schaffner", english: "ticket inspector/conductor" },
      { german: "die Straßenbahn", english: "tram" },
      { german: "die Schienen", english: "rails/tracks" },
      { german: "das Auto", english: "car" },
      { german: "das Motorrad", english: "motorcycle" },
      { german: "der Lastwagen", english: "truck/lorry" },
      { german: "das Verkehrsschild", english: "traffic sign" },
      { german: "das Benzin", english: "petrol/gasoline" },
      { german: "die Tanksäule", english: "petrol pump" },
      { german: "die Tankstelle", english: "petrol station/gas station" },
      { german: "die Notrufsäule", english: "emergency call box" },
      { german: "der Stau", english: "traffic jam" },
      { german: "der Verkehr", english: "traffic" },
      { german: "die Raststätte", english: "motorway services/rest stop" },
      { german: "der Parkplatz", english: "car park/parking lot" },
      { german: "der Omnibus", english: "bus/coach" },
      { german: "der Krankenwagen", english: "ambulance" },
      { german: "das Polizeiauto", english: "police car" },
      { german: "der Abschleppwagen", english: "tow truck" },
      { german: "die Müllabfuhr", english: "rubbish collection/refuse lorry" },
      { german: "das Feuerwehrauto", english: "fire engine" },
      { german: "die Autobahn", english: "motorway/highway" },
    ],
  },
  {
    id: "section-15",
    number: 15,
    name: "Im Supermarkt",
    words: [
      { german: "die Nudeln", english: "pasta/noodles" },
      { german: "die Haferflocken", english: "oats/porridge oats" },
      { german: "die Cornflakes", english: "cornflakes/cereal" },
      { german: "das Öl", english: "oil" },
      { german: "der Essig", english: "vinegar" },
      { german: "die Mayonnaise", english: "mayonnaise" },
      { german: "das Mehl", english: "flour" },
      { german: "der Zucker", english: "sugar" },
      { german: "die Bäckerei", english: "bakery" },
      { german: "die Verkäuferin", english: "shop assistant (f)" },
      { german: "die Tüte", english: "bag" },
      { german: "der Einkaufszettel", english: "shopping list" },
      { german: "der Einkaufswagen", english: "shopping cart/trolley" },
      { german: "das Salz", english: "salt" },
      { german: "die Papiertaschentücher", english: "paper tissues/tissues" },
      { german: "die Windeln", english: "nappies/diapers" },
      { german: "das Waschpulver", english: "washing powder/detergent" },
      { german: "der Kunde", english: "customer (m)" },
      { german: "die Kundin", english: "customer (f)" },
      { german: "das Kühlregal", english: "chilled shelf/fridge aisle" },
      { german: "die Tiefkühlkost", english: "frozen food" },
      { german: "die Tiefkühltheke", english: "frozen food counter" },
      { german: "die Fischtheke", english: "fish counter" },
      { german: "die Süßigkeiten", english: "sweets/candy" },
      { german: "der Flaschenkasten", english: "bottle crate" },
      { german: "die Kasse", english: "checkout/till" },
      { german: "die Einkaufstasche", english: "shopping bag" },
      { german: "die Sahne", english: "cream" },
      { german: "der Jogurt", english: "yogurt" },
      { german: "die Margarine", english: "margarine" },
      { german: "der Apfelsaft", english: "apple juice" },
      { german: "der Orangensaft", english: "orange juice" },
      { german: "die Flasche", english: "bottle" },
      { german: "das Mineralwasser", english: "mineral water" },
      { german: "die Kekse", english: "biscuits/cookies" },
      { german: "die Bonbons", english: "sweets/boiled sweets" },
      { german: "die Schokolade", english: "chocolate" },
      { german: "der Lutscher", english: "lollipop" },
      { german: "der Kaugummi", english: "chewing gum" },
    ],
  },

  {
    id: "section-16",
    number: 16,
    name: "Auf dem Markt",
    words: [
      { german: "der Blumenkohl", english: "cauliflower" },
      { german: "die Gurke", english: "cucumber" },
      { german: "die Karotte", english: "carrot" },
      { german: "die Kartoffel", english: "potato" },
      { german: "der Kürbis", english: "pumpkin" },
      { german: "der Lauch", english: "leek" },
      { german: "die Paprika", english: "bell pepper" },
      { german: "das Radieschen", english: "radish" },
      { german: "der Salat", english: "lettuce/salad" },
      { german: "die Tomate", english: "tomato" },
      { german: "die Zucchini", english: "zucchini/courgette" },
      { german: "die Zwiebel", english: "onion" },
      { german: "die Aubergine", english: "eggplant/aubergine" },
      { german: "die Erbsen", english: "peas" },
      { german: "die Bohnen", english: "beans" },
      { german: "die Champignons", english: "mushrooms" },
      { german: "die Petersilie", english: "parsley" },
      { german: "der Apfel", english: "apple" },
      { german: "die Banane", english: "banana" },
      { german: "die Birne", english: "pear" },
      { german: "die Erdbeere", english: "strawberry" },
      { german: "die Himbeere", english: "raspberry" },
      { german: "die Kirsche", english: "cherry" },
      { german: "die Kiwi", english: "kiwi" },
      { german: "die Orange", english: "orange" },
      { german: "der Pfirsich", english: "peach" },
      { german: "die Pflaume", english: "plum" },
      { german: "die Weintrauben", english: "grapes" },
      { german: "die Zitrone", english: "lemon" },
      { german: "die Ananas", english: "pineapple" },
      { german: "die Kokosnuss", english: "coconut" },
      { german: "die Melone", english: "melon" },
      { german: "die Nüsse", english: "nuts" },
      { german: "der Obststand", english: "fruit stall" },
      { german: "der Gemüsestand", english: "vegetable stall" },
      { german: "die Waage", english: "scale" },
      { german: "der Verkäufer", english: "salesperson (m)" },
      { german: "die Verkäuferin", english: "salesperson (f)" },
      { german: "der Korb", english: "basket" },
    ],
  },
  {
    id: "section-17",
    number: 17,
    name: "Im Zoo",
    words: [
      { german: "der Löwe", english: "lion" },
      { german: "der Tiger", english: "tiger" },
      { german: "der Elefant", english: "elephant" },
      { german: "das Zebra", english: "zebra" },
      { german: "die Giraffe", english: "giraffe" },
      { german: "das Nashorn", english: "rhinoceros" },
      { german: "das Krokodil", english: "crocodile" },
      { german: "das Nilpferd", english: "hippopotamus" },
      { german: "der Affe", english: "monkey" },
      { german: "der Gorilla", english: "gorilla" },
      { german: "der Orang-Utan", english: "orangutan" },
      { german: "der Panda", english: "panda" },
      { german: "der Bär", english: "bear" },
      { german: "der Wolf", english: "wolf" },
      { german: "der Fuchs", english: "fox" },
      { german: "das Känguru", english: "kangaroo" },
      { german: "das Kamel", english: "camel" },
      { german: "der Leopard", english: "leopard" },
      { german: "der Gepard", english: "cheetah" },
      { german: "der Pinguin", english: "penguin" },
      { german: "der Seehund", english: "seal" },
      { german: "der Wal", english: "whale" },
      { german: "der Delfin", english: "dolphin" },
      { german: "der Papagei", english: "parrot" },
      { german: "der Flamingo", english: "flamingo" },
      { german: "der Pfau", english: "peacock" },
      { german: "der Strauß", english: "ostrich" },
      { german: "der Adler", english: "eagle" },
      { german: "die Eule", english: "owl" },
      { german: "der Schwan", english: "swan" },
      { german: "die Schildkröte", english: "turtle/tortoise" },
      { german: "die Schlange", english: "snake" },
      { german: "das Aquarium", english: "aquarium" },
      { german: "der Käfig", english: "cage" },
      { german: "das Gehege", english: "enclosure" },
    ],
  },
  {
    id: "section-18",
    number: 18,
    name: "Im Krankenhaus",
    words: [
      { german: "der Arzt", english: "doctor (m)" },
      { german: "die Ärztin", english: "doctor (f)" },
      { german: "die Krankenschwester", english: "nurse" },
      { german: "der Patient", english: "patient (m)" },
      { german: "die Patientin", english: "patient (f)" },
      { german: "das Krankenhaus", english: "hospital" },
      { german: "der Krankenwagen", english: "ambulance" },
      { german: "das Wartezimmer", english: "waiting room" },
      { german: "das Bett", english: "bed" },
      { german: "das Thermometer", english: "thermometer" },
      { german: "das Stethoskop", english: "stethoscope" },
      { german: "die Spritze", english: "injection/syringe" },
      { german: "das Pflaster", english: "plaster/band-aid" },
      { german: "die Tablette", english: "tablet/pill" },
      { german: "die Medizin", english: "medicine" },
      { german: "die Salbe", english: "ointment/cream" },
      { german: "der Verband", english: "bandage" },
      { german: "die Krücken", english: "crutches" },
      { german: "der Rollstuhl", english: "wheelchair" },
      { german: "die Operation", english: "operation/surgery" },
      { german: "das Röntgenbild", english: "X-ray" },
      { german: "die Notaufnahme", english: "emergency room" },
      { german: "die Apotheke", english: "pharmacy" },
      { german: "die Untersuchung", english: "examination" },
      { german: "das Rezept", english: "prescription" },
    ],
  },
  {
    id: "section-19",
    number: 19,
    name: "In Wald und Wiese",
    words: [
      { german: "der Baum", english: "tree" },
      { german: "das Blatt", english: "leaf" },
      { german: "der Ast", english: "branch" },
      { german: "der Stamm", english: "trunk" },
      { german: "die Wurzel", english: "root" },
      { german: "die Blume", english: "flower" },
      { german: "das Gras", english: "grass" },
      { german: "der Pilz", english: "mushroom" },
      { german: "die Eichel", english: "acorn" },
      { german: "die Kastanie", english: "chestnut" },
      { german: "der Zapfen", english: "pine cone" },
      { german: "das Moos", english: "moss" },
      { german: "der Farn", english: "fern" },
      { german: "der Bach", english: "stream/brook" },
      { german: "der Stein", english: "stone/rock" },
      { german: "der Hügel", english: "hill" },
      { german: "der Wald", english: "forest/woods" },
      { german: "die Wiese", english: "meadow" },
      { german: "der Hase", english: "hare/rabbit" },
      { german: "das Reh", english: "deer/roe deer" },
      { german: "der Hirsch", english: "stag/deer" },
      { german: "das Wildschwein", english: "wild boar" },
      { german: "das Eichhörnchen", english: "squirrel" },
      { german: "der Igel", english: "hedgehog" },
      { german: "die Maus", english: "mouse" },
      { german: "der Maulwurf", english: "mole" },
      { german: "der Specht", english: "woodpecker" },
      { german: "das Rotkehlchen", english: "robin" },
      { german: "die Amsel", english: "blackbird" },
      { german: "die Krähe", english: "crow" },
      { german: "die Spinne", english: "spider" },
      { german: "die Ameise", english: "ant" },
      { german: "die Heuschrecke", english: "grasshopper" },
      { german: "der Käfer", english: "beetle" },
    ],
  },
  {
    id: "section-20",
    number: 20,
    name: "Auf dem Bauernhof",
    words: [
      { german: "die Kuh", english: "cow" },
      { german: "das Pferd", english: "horse" },
      { german: "das Schwein", english: "pig" },
      { german: "das Schaf", english: "sheep" },
      { german: "die Ziege", english: "goat" },
      { german: "das Huhn", english: "chicken/hen" },
      { german: "der Hahn", english: "rooster" },
      { german: "die Ente", english: "duck" },
      { german: "die Gans", english: "goose" },
      { german: "der Truthahn", english: "turkey" },
      { german: "der Esel", english: "donkey" },
      { german: "der Hund", english: "dog" },
      { german: "die Katze", english: "cat" },
      { german: "das Kaninchen", english: "rabbit" },
      { german: "die Maus", english: "mouse" },
      { german: "der Stall", english: "stable/barn" },
      { german: "die Scheune", english: "barn" },
      { german: "der Traktor", english: "tractor" },
      { german: "der Anhänger", english: "trailer" },
      { german: "der Heuballen", english: "hay bale" },
      { german: "das Feld", english: "field" },
      { german: "der Bauer", english: "farmer (m)" },
      { german: "die Bäuerin", english: "farmer (f)" },
      { german: "die Mistgabel", english: "pitchfork" },
      { german: "die Schubkarre", english: "wheelbarrow" },
      { german: "der Zaun", english: "fence" },
      { german: "das Futter", english: "feed/fodder" },
      { german: "die Eier", english: "eggs" },
      { german: "die Milch", english: "milk" },
      { german: "die Wolle", english: "wool" },
    ],
  },
  {
    id: "section-21",
    number: 21,
    name: "Am Meer",
    words: [
      { german: "das Meer", english: "sea/ocean" },
      { german: "der Strand", english: "beach" },
      { german: "der Sand", english: "sand" },
      { german: "die Wellen", english: "waves" },
      { german: "die Muschel", english: "shell" },
      { german: "der Seestern", english: "starfish" },
      { german: "die Qualle", english: "jellyfish" },
      { german: "die Krabbe", english: "crab" },
      { german: "der Krebs", english: "lobster/crayfish" },
      { german: "der Fisch", english: "fish" },
      { german: "das Segelboot", english: "sailboat" },
      { german: "das Schiff", english: "ship" },
      { german: "der Leuchtturm", english: "lighthouse" },
      { german: "die Insel", english: "island" },
      { german: "die Palme", english: "palm tree" },
      { german: "die Sonnencreme", english: "sunscreen" },
      { german: "das Handtuch", english: "towel" },
      { german: "der Sonnenschirm", english: "beach umbrella" },
      { german: "die Badehose", english: "swimming trunks" },
      { german: "der Badeanzug", english: "swimsuit" },
      { german: "die Taucherbrille", english: "diving goggles" },
      { german: "die Schwimmflossen", english: "flippers" },
      { german: "der Schwimmring", english: "swim ring" },
      { german: "die Luftmatratze", english: "air mattress" },
      { german: "der Eimer", english: "bucket" },
      { german: "die Schaufel", english: "spade" },
      { german: "die Sandburg", english: "sandcastle" },
      { german: "die Möwe", english: "seagull" },
      { german: "der Hafen", english: "harbor/port" },
      { german: "die Küste", english: "coast" },
    ],
  },
  {
    id: "section-22",
    number: 22,
    name: "Beim Sport",
    words: [
      { german: "der Fußball", english: "football/soccer" },
      { german: "der Basketball", english: "basketball" },
      { german: "der Volleyball", english: "volleyball" },
      { german: "der Tennisball", english: "tennis ball" },
      { german: "der Tennisschläger", english: "tennis racket" },
      { german: "der Hockeyschläger", english: "hockey stick" },
      { german: "die Schlittschuhe", english: "ice skates" },
      { german: "die Skier", english: "skis" },
      { german: "der Skihelm", english: "ski helmet" },
      { german: "der Schlitten", english: "sled" },
      { german: "das Surfbrett", english: "surfboard" },
      { german: "das Fahrrad", english: "bicycle" },
      { german: "der Roller", english: "scooter" },
      { german: "das Skateboard", english: "skateboard" },
      { german: "die Turnschuhe", english: "sneakers/trainers" },
      { german: "das Trikot", english: "jersey/kit" },
      { german: "die Medaille", english: "medal" },
      { german: "der Pokal", english: "trophy/cup" },
      { german: "der Sportplatz", english: "sports ground" },
      { german: "das Stadion", english: "stadium" },
      { german: "das Schwimmbad", english: "swimming pool" },
      { german: "der Wettkampf", english: "competition" },
      { german: "der Spieler", english: "player (m)" },
      { german: "die Spielerin", english: "player (f)" },
      { german: "der Trainer", english: "coach/trainer" },
      { german: "die Mannschaft", english: "team" },
      { german: "das Tor", english: "goal" },
      { german: "der Pfiff", english: "whistle (sound)" },
      { german: "die Gymnastik", english: "gymnastics" },
      { german: "das Rennen", english: "race" },
    ],
  },
  {
    id: "section-23",
    number: 23,
    name: "Was ich tue",
    words: [
      { german: "essen", english: "to eat" },
      { german: "trinken", english: "to drink" },
      { german: "schlafen", english: "to sleep" },
      { german: "laufen", english: "to run/walk" },
      { german: "springen", english: "to jump" },
      { german: "sitzen", english: "to sit" },
      { german: "stehen", english: "to stand" },
      { german: "lesen", english: "to read" },
      { german: "schreiben", english: "to write" },
      { german: "malen", english: "to paint/draw" },
      { german: "singen", english: "to sing" },
      { german: "tanzen", english: "to dance" },
      { german: "lachen", english: "to laugh" },
      { german: "weinen", english: "to cry" },
      { german: "sprechen", english: "to speak" },
      { german: "hören", english: "to hear/listen" },
      { german: "sehen", english: "to see" },
      { german: "denken", english: "to think" },
      { german: "lernen", english: "to learn" },
      { german: "spielen", english: "to play" },
      { german: "arbeiten", english: "to work" },
      { german: "helfen", english: "to help" },
      { german: "kochen", english: "to cook" },
      { german: "backen", english: "to bake" },
      { german: "waschen", english: "to wash" },
      { german: "duschen", english: "to shower" },
      { german: "baden", english: "to bathe" },
      { german: "kämmen", english: "to comb" },
      { german: "anziehen", english: "to put on (clothes)" },
      { german: "ausziehen", english: "to take off (clothes)" },
      { german: "öffnen", english: "to open" },
      { german: "schließen", english: "to close" },
      { german: "tragen", english: "to carry/wear" },
      { german: "werfen", english: "to throw" },
      { german: "fangen", english: "to catch" },
      { german: "fahren", english: "to drive/go" },
      { german: "schwimmen", english: "to swim" },
      { german: "klettern", english: "to climb" },
      { german: "graben", english: "to dig" },
      { german: "pflanzen", english: "to plant" },
      { german: "schneiden", english: "to cut" },
      { german: "kaufen", english: "to buy" },
      { german: "verkaufen", english: "to sell" },
      { german: "suchen", english: "to search/look for" },
      { german: "finden", english: "to find" },
      { german: "zeigen", english: "to show/point" },
      { german: "warten", english: "to wait" },
      { german: "winken", english: "to wave" },
    ],
  },
  {
    id: "section-24",
    number: 24,
    name: "Gegensätze",
    words: [
      { german: "groß", english: "big/tall" },
      { german: "klein", english: "small/short" },
      { german: "alt", english: "old" },
      { german: "jung", english: "young" },
      { german: "dick", english: "fat/thick" },
      { german: "dünn", english: "thin/slim" },
      { german: "lang", english: "long" },
      { german: "kurz", english: "short" },
      { german: "schnell", english: "fast/quick" },
      { german: "langsam", english: "slow" },
      { german: "heiß", english: "hot" },
      { german: "kalt", english: "cold" },
      { german: "hell", english: "bright/light" },
      { german: "dunkel", english: "dark" },
      { german: "laut", english: "loud" },
      { german: "leise", english: "quiet/soft" },
      { german: "stark", english: "strong" },
      { german: "schwach", english: "weak" },
      { german: "schwer", english: "heavy/difficult" },
      { german: "leicht", english: "light/easy" },
      { german: "voll", english: "full" },
      { german: "leer", english: "empty" },
      { german: "sauber", english: "clean" },
      { german: "schmutzig", english: "dirty" },
      { german: "offen", english: "open" },
      { german: "geschlossen", english: "closed" },
      { german: "nass", english: "wet" },
      { german: "trocken", english: "dry" },
      { german: "hoch", english: "high/tall" },
      { german: "niedrig", english: "low" },
      { german: "breit", english: "wide/broad" },
      { german: "schmal", english: "narrow" },
      { german: "glücklich", english: "happy" },
      { german: "traurig", english: "sad" },
      { german: "freundlich", english: "friendly/kind" },
      { german: "böse", english: "angry/mean" },
      { german: "früh", english: "early" },
      { german: "spät", english: "late" },
      { german: "nah", english: "near/close" },
      { german: "fern", english: "far/distant" },
    ],
  },
  {
    id: "section-25",
    number: 25,
    name: "Wetter, Jahreszeit und Monat",
    words: [
      { german: "die Sonne", english: "sun" },
      { german: "die Wolke", english: "cloud" },
      { german: "der Regen", english: "rain" },
      { german: "der Schnee", english: "snow" },
      { german: "der Wind", english: "wind" },
      { german: "der Nebel", english: "fog/mist" },
      { german: "das Gewitter", english: "thunderstorm" },
      { german: "der Blitz", english: "lightning" },
      { german: "der Donner", english: "thunder" },
      { german: "der Regenbogen", english: "rainbow" },
      { german: "die Jahreszeit", english: "season" },
      { german: "der Frühling", english: "spring" },
      { german: "der Sommer", english: "summer" },
      { german: "der Herbst", english: "autumn/fall" },
      { german: "der Winter", english: "winter" },
      { german: "der Januar", english: "January" },
      { german: "der Februar", english: "February" },
      { german: "der März", english: "March" },
      { german: "der April", english: "April" },
      { german: "der Mai", english: "May" },
      { german: "der Juni", english: "June" },
      { german: "der Juli", english: "July" },
      { german: "der August", english: "August" },
      { german: "der September", english: "September" },
      { german: "der Oktober", english: "October" },
      { german: "der November", english: "November" },
      { german: "der Dezember", english: "December" },
      { german: "warm", english: "warm" },
      { german: "kalt", english: "cold" },
      { german: "sonnig", english: "sunny" },
      { german: "regnerisch", english: "rainy" },
      { german: "windig", english: "windy" },
      { german: "bewölkt", english: "cloudy" },
      { german: "frostig", english: "frosty" },
    ],
  },
  {
    id: "section-26",
    number: 26,
    name: "Woche, Uhrzeit und Tageszeit",
    words: [
      { german: "der Montag", english: "Monday" },
      { german: "der Dienstag", english: "Tuesday" },
      { german: "der Mittwoch", english: "Wednesday" },
      { german: "der Donnerstag", english: "Thursday" },
      { german: "der Freitag", english: "Friday" },
      { german: "der Samstag", english: "Saturday" },
      { german: "der Sonntag", english: "Sunday" },
      { german: "die Woche", english: "week" },
      { german: "das Wochenende", english: "weekend" },
      { german: "der Morgen", english: "morning" },
      { german: "der Vormittag", english: "late morning" },
      { german: "der Mittag", english: "noon/midday" },
      { german: "der Nachmittag", english: "afternoon" },
      { german: "der Abend", english: "evening" },
      { german: "die Nacht", english: "night" },
      { german: "die Uhr", english: "clock" },
      { german: "die Armbanduhr", english: "wristwatch" },
      { german: "der Wecker", english: "alarm clock" },
      { german: "die Minute", english: "minute" },
      { german: "die Sekunde", english: "second" },
      { german: "die Stunde", english: "hour" },
      { german: "heute", english: "today" },
      { german: "morgen", english: "tomorrow" },
      { german: "gestern", english: "yesterday" },
      { german: "früh", english: "early" },
      { german: "spät", english: "late" },
    ],
  },
  {
    id: "section-27",
    number: 27,
    name: "Formen und Farben",
    words: [
      { german: "der Kreis", english: "circle" },
      { german: "das Quadrat", english: "square" },
      { german: "das Rechteck", english: "rectangle" },
      { german: "das Dreieck", english: "triangle" },
      { german: "der Stern", english: "star" },
      { german: "das Herz", english: "heart" },
      { german: "die Linie", english: "line" },
      { german: "der Punkt", english: "dot/point" },
      { german: "rot", english: "red" },
      { german: "blau", english: "blue" },
      { german: "grün", english: "green" },
      { german: "gelb", english: "yellow" },
      { german: "schwarz", english: "black" },
      { german: "weiß", english: "white" },
      { german: "grau", english: "grey" },
      { german: "braun", english: "brown" },
      { german: "rosa", english: "pink" },
      { german: "orange", english: "orange" },
      { german: "lila", english: "purple" },
      { german: "bunt", english: "colorful" },
      { german: "hell", english: "light (shade)" },
      { german: "dunkel", english: "dark (shade)" },
    ],
  },
  {
    id: "section-28",
    number: 28,
    name: "Zahlen",
    words: [
      { german: "null", english: "zero" },
      { german: "eins", english: "one" },
      { german: "zwei", english: "two" },
      { german: "drei", english: "three" },
      { german: "vier", english: "four" },
      { german: "fünf", english: "five" },
      { german: "sechs", english: "six" },
      { german: "sieben", english: "seven" },
      { german: "acht", english: "eight" },
      { german: "neun", english: "nine" },
      { german: "zehn", english: "ten" },
      { german: "elf", english: "eleven" },
      { german: "zwölf", english: "twelve" },
      { german: "dreizehn", english: "thirteen" },
      { german: "vierzehn", english: "fourteen" },
      { german: "fünfzehn", english: "fifteen" },
      { german: "sechzehn", english: "sixteen" },
      { german: "siebzehn", english: "seventeen" },
      { german: "achtzehn", english: "eighteen" },
      { german: "neunzehn", english: "nineteen" },
      { german: "zwanzig", english: "twenty" },
      { german: "dreißig", english: "thirty" },
      { german: "vierzig", english: "forty" },
      { german: "fünfzig", english: "fifty" },
      { german: "sechzig", english: "sixty" },
      { german: "siebzig", english: "seventy" },
      { german: "achtzig", english: "eighty" },
      { german: "neunzig", english: "ninety" },
      { german: "hundert", english: "hundred" },
      { german: "tausend", english: "thousand" },
    ],
  },
];

export const BOOK_STORAGE_KEY = "vocab_book_progress_v1";
export const BOOK_ADDED_SETS_KEY = "vocab_book_added_sets_v1";

// Which sections have been added to My Sets
export type BookProgress = Record<string, boolean>; // sectionId -> added
